name: dart_site
description: Dart Site

dependencies:
  angular: ^5.0.0-beta
  angular_components: ^0.9.0-beta


environment:
  sdk: '>=2.0.0 <3.0.0'

dev_dependencies:
  angular_test: ^2.0.0-beta
  build_runner: ^0.10.0
  build_test: ^0.10.2
  build_web_compilers: ^0.4.0
  test: ^1.0.0
